#!/bin/bash -e

# Script to run unit test
#
if ! which pyang >/dev/null 2>&1 ; then
    sudo pip install pyang
fi

pyang -f tree yang-models/*.yang -p ./ -Wnone

pyang --ietf yang-models/*.yang -p ./ -Wnone
